# Dockerfile.mqttclient

FROM debian:latest

# Install basic IP tools and mosquitto clients
RUN apt-get update && \
    apt-get install -y iputils-ping iproute2 mosquitto-clients && \
    rm -rf /var/lib/apt/lists/*

# Set the entry point
ENTRYPOINT ["/bin/sh", "-c", "mosquitto_sub -F '@Y-@m-@dT@H:@M:@S@z : %q : %t : %p' -h ${BROKER:-mqttdev} -t '#'"]
