#!/usr/bin/env python

MQTT_DEFAULT_CLIENT_ID = "mqtt2kasa"
MQTT_DEFAULT_CLIENT_TOPIC_FORMAT = "/kasa/device/{}"
MQTT_DEFAULT_BROKER_IP = "192.168.10.238"
MQTT_DEFAULT_RECONNECT_INTERVAL = 13  # [seconds]
KASA_DEFAULT_POLL_INTERVAL = 10  # [seconds]
KASA_DEFAULT_EMETER_POLL_INTERVAL = 0  # [seconds] 0 == disabled
KEEP_ALIVE_DEFAULT_TASK_INTERVAL = 1.5  # [seconds]
KASA_DEFAULT_THROTTLE_RATE_LIMIT = 4  # 0 == disabled
KASA_DEFAULT_THROTTLE_PERIOD = 60
KASA_DEFAULT_RECEIVE_QUEUE_SIZE = 4  # 0 == queue is disabled