name: Build and Publish Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mqtt2kasa:${{ github.event.inputs.tag || github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          context: .

      - name: Logout from DockerHub
        run: docker logout
